# Image de base Kali Linux officielle
FROM kalilinux/kali-rolling

# Évite les interactions pendant les installations
ENV DEBIAN_FRONTEND=noninteractive

# Mise à jour et installation d'outils de pentest de base
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y nmap curl git && \
    apt-get clean

# Définit le dossier de travail
WORKDIR /root

# Commande par défaut au lancement du conteneur
CMD ["/bin/bash"]