---
- name: Déploiement de l'application mobile Kotlin avec Docker
  hosts: localhost
  connection: local
  vars:
    project_dir: /tmp/my-kotlin-app
    repo_url: "https://github.com/hassnae2003/App_AbsenceManager.git"
    container_name: kotlin_app_container
    docker_image: kotlin-app:latest
    apk_output_path: app/build/outputs/apk/debug/app-debug.apk

  tasks:

    - name: Cloner le projet Kotlin depuis GitHub
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        force: yes

    - name: Donner les permissions d'exécution à gradlew
      file:
        path: "{{ project_dir }}/gradlew"
        mode: "0755"

    - name: Compiler l'application Kotlin (APK)
      command: ./gradlew assembleDebug
      args:
        chdir: "{{ project_dir }}"

    - name: Créer une image Docker contenant l'APK
      docker_image:
        name: "{{ docker_image }}"
        build:
          path: "{{ project_dir }}"
          dockerfile: Dockerfile
      become: true

    - name: Supprimer l'ancien conteneur s’il existe
      docker_container:
        name: "{{ container_name }}"
        state: absent
      become: true

    - name: Lancer le conteneur Docker avec l'application Kotlin
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
      become: true
