---
- name: Déploiement de l'application mobile Kotlin et hébergement APK via Apache Docker
  hosts: localhost
  connection: local
  vars:
    project_dir: /tmp/my-kotlin-app
    repo_url: "https://github.com/hassnae2003/App_AbsenceManager.git"
    container_name: kotlin_apache_container
    docker_image: kotlin-apache-server:latest
    apk_output_path: app/build/outputs/apk/debug/app-debug.apk
    apache_build_dir: /tmp/apache-server

  tasks:

    - name: Cloner le projet Kotlin depuis GitHub
      git:
        repo: "{{ repo_url }}"
        dest: "{{ project_dir }}"
        force: yes

    - name: Donner les permissions d'exécution à gradlew
      file:
        path: "{{ project_dir }}/gradlew"
        mode: "0755"

    - name: Compiler l'application Kotlin (APK)
      command: ./gradlew assembleDebug
      args:
        chdir: "{{ project_dir }}"

    - name: Créer le dossier pour Apache Docker build
      file:
        path: "{{ apache_build_dir }}"
        state: directory

    - name: Copier l'APK dans le dossier Apache
      copy:
        src: "{{ project_dir }}/{{ apk_output_path }}"
        dest: "{{ apache_build_dir }}/app-debug.apk"

    - name: Copier le Dockerfile Apache dans le dossier apache-server
      copy:
        src: ansible/Dockerfile.apache
        dest: "{{ apache_build_dir }}/Dockerfile"

    - name: Construire l'image Docker Apache avec APK
      docker_image:
        name: "{{ docker_image }}"
        build:
          path: "{{ apache_build_dir }}"
        state: present
      become: true

    - name: Supprimer l'ancien conteneur s’il existe
      docker_container:
        name: "{{ container_name }}"
        state: absent
      become: true

    - name: Lancer le conteneur Docker Apache avec l'APK
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        published_ports:
          - "8080:80"
      become: true
