name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Install Ansible and Docker
        run: |
          sudo apt update
          sudo apt install -y ansible
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Run Ansible playbook to build Docker image and deploy Apache with APK
        run: ansible-playbook ansible/playbook.yml -i ansible/inventory.yml

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk-debug
          path: /tmp/my-kotlin-app/app/build/outputs/apk/debug/app-debug.apk
